### ISSUE TITLE
Inline-block grids

### ISSUE THREAD

**Issue by evamichalcak** [oddbird/susy#478]
I am new to Suzy and it seems very flexible, but nevertheless it seems not to be able to produce non-float grids (i.e. Griddle: http://necolas.github.io/griddle/).
These grids use inline-block and box-sizing to provide features that float-based layouts cannot and work very nicely for galleries. It seems it would be quite easy to implement a mixin to cover those grids too, as an alternative to isolate-galleries

**Comment by ericam** [comment]
We've talked about inline-block options before, but there are so many white-space gotcha's it was never clear how to make it reliable across projects. The margin trick *requires* extra markup, and the letter-spacing hack is inexact depending on your fonts. 

I don't know that we'll add it to the core, but that doesn't mean you shouldn't do it with Susy! The real flexibility & power of Susy is in the functions, which you can use to build anything. They use the same syntax as the mixins, but let you apply the results to any property you want:

```scss
.grid-cell {
  display: inline-block;
  padding: 0 gutter();
  width: span(3);
}
```

Play around with that. If you find a robust solution that you think would work in the Susy core, I'll be happy to consider it. Cheers!

**Comment by robsonsobral** [comment]
Hi! May I step into the discussion?

[PureCSS](http://purecss.io/grids/) found its [way out of this problem](http://blog.purecss.io/post/60789414532/how-we-improved-grids-in-pure-030). The Android Browser started to support custom fonts on [version 2.2](http://caniuse.com/#search=font-face). I'm sorry, but O'm not sure about the format. I guess Android browser uses TTF on old versions and WOFF on new ones.

Matthew Lein had [an interesting idea](https://matthewlein.com/articles/inline-block-no-space-font/) on using a 0 width font. He even created [the file](https://github.com/matthewlein/inline-block-no-space-font). But the `padding: 0 1px; /* Firefox fix */` scares me.

I like the `font-size: 0` technique. It's easy to implement and has a good support, except for the old [Android native browser](http://codepen.io/stowball/details/LsICH).

I guess, between the options, you can pick one. My vote is the used by PureCSS, because they've have implemented it for quite some time.

I know @HugoGiraudel isn't a fan of any of these techniques, but they can bring some good improvements in my opinion:

- centralize a grid of items;
- vertical align items;
- distribute items on space;

Flex-box is something I try to avoid when I can. It inserts a new level of complexity to the code and to the browser render engine.

Thank you for the attention and for Susy!

**Comment by HugoGiraudel** [comment]
> I know @HugoGiraudel isn't a fan of any of these techniques

I’d be curious to know where you get that from. :)

**Comment by robsonsobral** [comment]
I've [mind reading powers](https://css-tricks.com/fighting-the-space-between-inline-block-elements/#comment-166755)!

> I also think it’s better to use the HTML way (no carriage return or HTML comments) because every CSS method rely on browser inconsistencies, which is as we know, not very reliable.

> Though I never been faced to such a problem, but I guess I’d use the no carriage way. Seems the less tricky.

---

I've mentioned you, @HugoGiraudel, because I believe you're helping to next version. Am I wrong?

---

I've just found another [repository of zero width fonts](https://github.com/patrickkunka/zero-width) created for this situation, but, this time, with no mention to a Firefox bug fix.

```css
.grid {
    font-family: 'zero-width';
    font-size: 0;
}

.grid .item {
    font-family: 'helvetica';
    font-size: 1rem; 
}
```

**Comment by HugoGiraudel** [comment]
Ah, interesting. I have no memories of this comment but it’s funny how I didn’t change my mind on this topic. After 4 years, I find it impressive; most of my opinions from that time completely changed.

Anyway, I still believe it’s easier to rely on markup fixes when possible. :)

**Comment by robsonsobral** [comment]
I knew it!

**Comment by mirisuzanne** [comment]
Clever hacks! Also, Hugo has helped on the third version! And I agree with Hugo's assessment! :)

Susy 3 will be even less opinionated than Susy 2 — meaning we're likely to remove floats, not add in other layout techniques (inline-block, flexbox, etc). Susy should work with any layout system, as demonstrated above, but I'm not interested in maintaining a library of hacks for inline-block, float, flex, or anything else. Susy 3 will do the grid math, and leave the decisions to you.

**Comment by esr360** [comment]
Just FYI, I don't know if this feature is still planned, but the whitespace issue can be solved relatively easily using only CSS - here's how I solved it: https://github.com/esr360/Kayzen-GS/blob/master/src/core/row/_core.scss

The key to the trick is setting `display: table;` and `width: 100%;` on the row element. This solves the issue for Webkit browsers, and for Firefox/IE, the `letter-spacing: -1em;` hack works consistently regardless of typeface used.

As far as I'm aware, this technique isn't that well known, so just thought I'd share for reference.

**Comment by robsonsobral** [comment]
@esr360 , it's an interesting solution. Does it still works with multiple rows without a wrapper for every one? This is a main `inline-block` advantage over other techniques.

Bbbbbbbbbbbbbut, as pointed here, Susy 3 will be "layout technique agnostic".

**Comment by esr360** [comment]
@robsonsobral, yes I believe it does. If I understand you correctly you are referring to something like: http://esr360.github.io/Kayzen-GS/#flow-columns

But yes as you say, it's a bit of a moot point, but something I thought was relevant nonetheless.
