### ISSUE TITLE
Create float/isolate plugin

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/susy#514]

**Comment by HugoGiraudel** [comment]
We also need to figure out what is the best way to handle plugins:

* `plugins/` folder
* plugin repositories (in a `susy` organisation?)

We should also be quite clear that a plugin should touch the core in any way.

**Comment by ericam** [comment]
plugins folder will simplify usage, but be less modular. I might lean towards separate repos, but I'd be happy for other opinions.

**Comment by zellwk** [comment]
I'd vote for `plugins/` folder simply because it simplifies usage. We can encourage people to submit `pull` requests for the plugins they have created to make it more modular. Besides, it's easier to `require susy` once versus to requiring 3-4 different repos everytime they want to use Susy. 

The shift we're going for is largely an educational issue as opposed to a categorisation issue.

**Comment by mabar** [comment]
Plugins are still imported same way, so plugins from oddbird can be in plugins folder for simplicity and plugins from other vendors can still have their own packages.

**Comment by mirisuzanne** [comment]
Yeah, after playing with it, I'm fairly confident we'll need to ship *some* small plugins along with the core - enough to get people started. But I do hope to keep those minimal.

**Comment by mirisuzanne** [comment]
There will be no output-generating plugins at this point – only the grid image. Everything else will be handled in tutorials.
