### ISSUE TITLE
Isolation technique caveats?

### ISSUE THREAD

**Issue by corysimmons** [oddbird/susy#568]
In various docs/tutorials I've seen it mentioned that isolation technique fixes subpixel rounding errors, but it shouldn't be used all the time.

Why not?

**Comment by mirisuzanne** [comment]
"Shouldn't" is a strong word, but I don't recommend it for a few reasons (though the trade-offs may be different for you):

- Layout elements are removed from the flow in a way that makes relationships unclear. Using isolation everywhere would be similar to using `position: absolute` for everything on a site.
- It uses a lot of extra code to achieve a relatively small browser-bug workaround. That code isn't just bloating the output, but it affects the rest of your styles:
- Right margins are used-up and can't be touched. Left-margins are used for positioning off the container, so become meaningless in relation to other elements. 
- The code doesn't make sense when you read it, and you can't work with it in the ways you expect to. That's a problem because it can be fragile, and break in confusing ways.

As a design preference: I want to be robust enough that a design can handle errant pixels here or there — otherwise I feel like I'm fighting against the grain of the web as a medium. It's the same reason I don't recommend putting much effort into baseline grids. It's a lot of work, for a little (fragile) payoff. That trade is only worthwhile on small widgets like an image gallery where 1) it has more impact because galleries can multiply the effect of sub-pixel rounding, and 2) I only need it to do one thing, so it's more contained and manageable.

Hope that helps! I'm not here to tell other developers what will work best for their projects. You should do what works best for you!

**Comment by corysimmons** [comment]
Thanks for the in-depth explanation.

Btw, kudos on Susy. It's super flexible.

**Comment by tsi** [comment]
That's a great answer, I'd just like to add that for me, since the 'isolation' or 'container-relative floats' technique allows you to position elements in any order you want (horizontally), it is being used mainly for source order manipulation much more frequently then to tackle the rounding issue.

**Comment by mirisuzanne** [comment]
Yeah, that's a cool use. I've also used it to make equal-height tabs that wrap the largest content by stacking isolated floats on top of each other. Nifty for little tricks like that.
