### ISSUE TITLE
I not know how getting started susy if i use 'gulp'

### ISSUE THREAD

**Issue by semiromid** [oddbird/susy#584]
Help please me. I not know how getting started susy if i use 'gulp'.  not want use 'compass'.

**Comment by mirisuzanne** [comment]
@aaronagray - would you be able to add a `gulp` section to the getting-started guide? We should probably also move Compass down the list, since it is end-of-life.

**Comment by semiromid** [comment]
would you be able to add a gulp section to the getting-started guide?  --- Yes, need add guide, how  getting-started use witch `gulp `. Thanks.

**Comment by semiromid** [comment]
> would you be able to add a gulp section to the getting-started guide?

 Maybe. I yet not know.

**Comment by semiromid** [comment]
I make it -` "@import "node_modules/susy/sass/susy;"`   But give error -

>  Error: no mixin named clearfix

**Comment by semiromid** [comment]
Like this i it make - ```
@import "node_modules/susy/sass/susy";
@import "node_modules/breakpoint-sass/stylesheets/breakpoint";
```

It is good ?

**Comment by semiromid** [comment]
And like this yet 
**gulpfile.js**
```
var path = require('path'),
susy_main = require.resolve('susy'), 
susy_dir  = path.dirname(susy_main); 

//SCSS
gulp.task('sass', function () {
    gulp.src('./src/sass/**/*.scss')
    .pipe(sass({includePaths: [susy_dir]}))
    .pipe(sass.sync().on('error', sass.logError))
    .pipe(gulp.dest('./src/css/css/'));
});
```
**test_style.scss**
`@import "_susy";`

It is good ?

**Comment by aaronagray** [comment]
@mirisuzanne sounds good! I'll take a look this weekend.

**Comment by zellwk** [comment]
I already have a guide about this somewhere in my sample chapters. I can add it easily when I'm back from my holidays :) 

Stay awesome! 
Zell

**Comment by FNGR2911** [comment]
Hey everybody. Got it working by doing:
```
npm install susy --save-dev
```

and in my gulpfile:
```
gulp.task('sass', function() {
    return gulp.src('scss/*.scss')
        .pipe(sass({
            outputStyle: 'compressed',
            includePaths: ['node_modules/susy/sass']
        }).on('error', sass.logError))
        .pipe(gulp.dest('dist/css'));
});
```

works fine 👍

**Comment by semiromid** [comment]
FNGR2911 - Thanks!

**Comment by FNGR2911** [comment]
Is it working for you too @semiromid? I wrote an update to the docs and made a PR @mirisuzanne

**Comment by semiromid** [comment]
@FNGR2911 , yes `@import "_susy";` Good work. 

> I wrote an update to the docs and made a PR @mirisuzanne 

Thanks you. Did It need make  me?

**Comment by mirisuzanne** [comment]
Thanks, everyone!

**Comment by simonron** [comment]
I don't see clearfix working ? The mixin was missing, so I added it, no error now, but it doesn't work.

**Comment by mirisuzanne** [comment]
@simonron I don't think your question is related to this thread, would you like to open a new issue? 

I also need more information about your code in order to help. Where is the clearfix not working? What mixin were you trying to use? We don't have a mixin called `clearfix`. Ours is called `susy-clearfix`, and it's not documented as part of the public API — only used internally. I'm not sure what you mean when you say it was missing, or what you did to replace it, or where you were expecting it to work.

**Comment by simonron** [comment]
Many thanks - I’ll work on this a while longer before re-posting !

On 26 Nov 2016, at 17:56, Miriam Suzanne <notifications@github.com> wrote:

@simonron <https://github.com/simonron> I don't think your question is related to this thread, would you like to open a new issue?

I also need more information about your code in order to help. Where is the clearfix not working? What mixin were you trying to use? We don't have a mixin called clearfix. Ours is called susy-clearfix, and it's not documented as part of the public API — only used internally. I'm not sure what you mean when you say it was missing, or what you did to replace it, or where you were expecting it to work.
