### ISSUE TITLE
Default clearing for the last col +1 to force correct order

### ISSUE THREAD

**Issue by jackblackCH** [oddbird/susy#593]
I don't see a reason why not to add default clearing to the latest column + 1 when using span()?. 
This would fix the wrong order of the next item, if you want to use the grid option for a gallery.

PS:I know there is the gallery() method but it produces ugly minus margins which are not necessary compared to this solution

i.e span(4 of 12) ->
output
```
<div class="grid-layout-4-of-12">
   <div>col1</div>
  <div>col2</div>
  <div>col3</div>
  <div>col4</div>
  <div>col5</div>
  <div>col6</div>
</div>

.grid-layout-4-of-12 {
	> div {
           @include span(4 of 12); 
	}
}

```
Should produce an automatic clear of the number of span + 1 (4n+1):
```
.grid-layout-4-of-12 > div {
    width: 25%;
}

.grid-layout-4-of-12 > >div:nth-of-type(4n+1) {
    clear: left;
}
````
This auto clearing would enable the "gallery" style even for all grids! without adding the nth-child stuff by yourself!

**Comment by mirisuzanne** [comment]
Hi @jackblackCH,

That would be a handy solution for your use-case, but it's not one that we can assume for all the uses for `span`. Sass doesn't have access to your DOM structure, so Susy only knows *exactly what you tell it*. When you say `span(4 of 12)`, Susy has no knowledge about how many elements you are applying that to, or what their relationships are. We can't just assume that `span` is being used on a set of equal-width siblings.

But Susy is built to be extended, because users like you will always be smarter about the exact specs you need for your project. I recommend writing that extension and sharing it with the community! I'd be happy to pass it around.

The gallery tool is very specifically designed to handle this one use-case *while eliminating sub-pixel rounding issues*. If you don't have an issue with sub-pixel rounding, I agree that the gallery output is overkill for you. But the gallery mixin is exactly what happens when we try to solve very specific use-cases, instead of giving you the tools to solve it yourself — in the end, it's bulkier than you want for most problems.
