### ISSUE TITLE
Default gutters don't work anymore (in my understanding)

### ISSUE THREAD

**Issue by dancinglightning** [oddbird/susy#610]
Hi, 
I've been using susy for a year and don't start a new project without anymore. Great and thanks!

Just having started a new one with susy-2.2.12, sass-3.4.22 and sass-rails-5.0.4 , the spans don't add up anymore. So when i just `import "susy"`  and  `include span(6 of 12)`, i get 
```
width: 50%;
float: left;
margin-right: 5.26316%;
```
which off course means two of those won't go next to each other.
Only when i configure ` $susy: ( gutter-position: inside)` do i get
```
width: 50%;
float: left;
padding-left: 2.5%;
padding-right: 2.5%;

```
and can have two same sized column. Now i'm happy to do the declaration and even more so if i am barking up the wrong tree entirely. But since it was so unexpected i thought i mention it, as a documentation issue maybe?

Thanks for susy,
Tosrten

**Comment by mirisuzanne** [comment]
I've tried several times in different ways, and can't recreate this problem — either the width or margin output. I consistently get the expected output:

```scss
.test {
  width: 49.15254%;
  float: left;
  margin-right: 1.69492%;
}
```

The only difference in my system is that I don't have `sass-rails` set up — but I'm not sure how that would change the math. I also can't think of a setting that would give the output you see.

I can recreate your gutter output (`5.26316%`) by calling the gutter mixin directly without arguments, which is appropriate for the default 4-column context. But `50%` width is only appropriate for `inside` or `0` gutters. Are you sure you don't have any other code that might be affecting things?

**Comment by dancinglightning** [comment]
Hi @mirisuzanne 

I actually copied the numbers from sassmeister, just to be sure it's not my system. But maybe i made a mistake, i was a bit flustered. Let's assume so, as i now get your numbers too :-(

But my point works with your numbers too, meaning two of those test classes won't go side by side.

Having read more (after posting) i can see that the default gutter _after_ is what got me. I had all my other projects set up with "inside" and assumed it was the default.
To my defence, i feel i was guided in this assumption by the getting started docs: It sort of says import susy and use span(6 of 12).
What it fails to say is that you have to use span(6 of 12 at 7) for the second column (or remove the margin by other means). I know it says it in the gutter options somewhere, which is where i found it an hour or two later.

This was my issue, it was just my understanding and possibly documentation.

Having thought about it, i can really see why gutters "after" would be the default for a professional designer. I guess it's the only way to make things line up perfectly in nested grids or different sized columns. Here we see that i am just a programmer, though i shall take this lesson to heart.

Thanks for checking, 
Torsten

**Comment by mirisuzanne** [comment]
Hi @dancinglightning — I'm glad the problem's been solved. I'm still curious how it happened. In either case, you're right that "after" is a strange default, because "inside" is much simpler and easier to use. You aren't missing something. I highly recommend using inside gutters. "After" is only the default for legacy reasons. When Susy 2 was released, most developers still couldn't count on `box-sizing` support in all browsers. Outside gutters were the only option that would work for everyone, and margin-right was the classic solution developers were used to. Every grid system at the time required special handling for the last gutter in a row — so we may not have documented that as well as we should. Since then, we've just been waiting for a major release to change the defaults. 

Susy 3 is very close. The core is likely stable, but I need to spend some time writing new documentation and tutorials. It's hard to stay flexible *and* make sure every use-case is well-documented — but we'll do what we can!

Thanks for being proactive, and providing feedback when you ran into confusion. I'm always glad to have people interacting!

**Comment by dancinglightning** [comment]
Hi @mirisuzanne 
glad to hear about susy 3, and thank you for responding so well to my confusion.
I have really been enjoying susy, so if there is any small thing a developer can do, you're welcome to call on me. Proofreading new stuff eg.

I also have an issue with the c version of sass & rails. I found the solution by googling, but if you want i can open an issue and document it.

**Comment by mirisuzanne** [comment]
Always good to file issues if you run into problems on open-source software. Just be sure to find the right channel (probably https://github.com/sass/libsass ?) and provide all the details you can about re-producing the problem. Happy coding!
