### ISSUE TITLE
L12 /language/_validation.scss: Functions can only contain variable declarations and control directives.

### ISSUE THREAD

**Issue by freddurst1805** [oddbird/susy#627]
Using the `compass watch` command, I get this error I don't know why, that stops the compilation so I actually cannot run Susy at all.
I remember when I installed Susy manualy, this error never showed up and I used the library without a problem, compiling with the command `sass --watch sass:css`.

Can someone help on this issue that is really problematic now that I need to put the application in production phase !!

Thank you very much :)

**Comment by mirisuzanne** [comment]
That line is an `@error` declaration. I don't know why your compiler is choking on that, unless you are using an old version of Sass and Compass. Do you know what versions you are using? Are you aware that Compass is end-of-life, and is to being maintained? 

The error you should likely be seeing is this one: `Static math requires a valid column-width setting`. That means you've likely set `math: static`, but you have not set `column-width`. Is that true?

**Comment by freddurst1805** [comment]
I get Compass 1.0.3 and Sass 3.3.14.
The problem here is I try to use Breakpoint in combination with Susy, and so I can't upgrade the Sass version more than this one, otherwise it's a conflict with Breakpoint ...
Did you ever manage to combine those two librairies ?

Thank you for you reactivity :)

**Comment by freddurst1805** [comment]
I don't even have an idea how to install both librairies and combine them without using Compass by the way.
I would love to avoid it :D

**Comment by mirisuzanne** [comment]
Looks like `@error` was added to Sass 3.4, so that's your problem. I recommend ditching Compass and upgrading Sass. Susy and Breakpoint were designed to work together, and neither one requires Compass any more. 

In Ruby environments, Compass helped simplify the import process for third-party tools. I'm not an expert on Ruby environments, but maybe [our docs will help](http://susydocs.oddbird.net/en/latest/install/)? I'm don't work in a Ruby environment, so I would install both Susy and Breakpoint through npm, and then load them with a direct import path (`@import '../npm_modules/susy/sass/susy`) or through gulp, webpack, or eyeglass. Most of that is outside my (Sass/CSS) expertise, but I bet we could get more help in here if you need it. :)

**Comment by freddurst1805** [comment]
Yeah it's exactly what I did but I have this Sass version's conflict that made things really hard !
I finally juste managed to install both libraries manually and auto-compile Sass with the old command I used to use to compile Susy alone.
I works like a charm :) Thank you very much for your support !

**Comment by mirisuzanne** [comment]
Great! I'm glad it's working!
