### ISSUE TITLE
Getting started with Susy 3

### ISSUE THREAD

**Issue by rizqinizamil** [oddbird/susy#631]
I'm pretty curious to try Susy 3 and start building my grids. But unfortunately I still don't get enough information from the documentation to get started. (I'm sorry, maybe that's my fault because I always need clear documentation to start something new).

I have 2 questions/problems so far (because I just get started):

1. I believe you ever mention on one of the thread here that on Susy 3 we don't need container. So how to define the container? Should we define manually? Not put it in the configuration map like Susy 2? Maybe you can give us sample code to build simple grid on Susy 3.
2. I got this error
```
Error: [susy-parse] Unknown shorthand property: [null] ``
        on line 59 of node_modules/susy/sass/susy/_utilities.scss
>>   @error '[#{$source}] #{$message}';
```
 when I put `margin-right: gutter()`. Any thoughts?

Thank you.

**Comment by robsonsobral** [comment]
related to https://github.com/oddbird/susy/issues/630

**Comment by mirisuzanne** [comment]
Not your fault. Lack of documentation is the main reason we haven't done a stable release.

For your first question: yes, create containers however you like. You can use the `span` function for width, if you want it based on grid math. Everything else will depend what you want it to do. If you're using floats, add a clearfix. If you want it centered, add auto margins. The default Susy2 container would look something like this:

```scss
.container {
  @include clearfix; // this is not provided yet in Susy 3
  margin: 0 auto;
  width: span(all);
}
```

You can turn that into a mixin, if you need to use it multiple places. Not that the clearfix mixin is not provided yet in Susy 3. I think it might make sense to add a "utilities" plugin with some of those common layout needs.

your second question is a duplicate of #630, I think, but helpful to know where the problem is coming from! I'll try to get a patch out soon, unless someone else wants to dig into that.

**Comment by rizqinizamil** [comment]
Thank you very much @mirisuzanne !

**Comment by HectorLS** [comment]
hello @mirisuzanne i have search a similar issue
