### ISSUE TITLE
Debug image grids are not aligned properly

### ISSUE THREAD

**Issue by Jakobud** [oddbird/susy#632]
I don't know if this has been an issue for a while or not, but the `debug: ( images: true` )` background grid boxes don't align with the generated grid.

Example: http://codepen.io/michellebarker/pen/gpRLQX

![screenshot 151](https://cloud.githubusercontent.com/assets/87356/25603343/294a2696-2eb8-11e7-8a2f-f17beccc7ed8.jpg)

Any clues on this? I didn't see any issues that seemed to be related to this.

**Comment by Jakobud** [comment]
Also, I can't really tell exactly if it's the grid that is incorrect or the background images. I think its the background but I'm not sure.

**Comment by mirisuzanne** [comment]
This is a known issue in browsers. Subpixel rounding is unreliable on background images. If you resize your window, you'll see the image bounce into place every few pixels. This is [noted in the docs](http://susydocs.oddbird.net/en/latest/toolkit/#show-grid), and fixed in Susy 3 by using inline-SVG instead of background gradients. Browsers handle subpixel rounding better on elements, so your grid is more accurate than the background. Don't try to use it for px-exact alignment without first re-sizing the window to a divisible width.

**Comment by Jakobud** [comment]
Yeah sorry I realized that after making this. It looks like v3 is taking care of all of this. Thanks!!
