### ISSUE TITLE
Offsetting doesn't work

### ISSUE THREAD

**Issue by souljacker** [oddbird/susy#635]
Using `@include span (6 at 4 of 12);` makes absolute no difference on the generated CSS.

Does offsetting work at all?

**Comment by mirisuzanne** [comment]
Sorry that's not clear in the docs – `at` has three uses, depending on your other settings:

- Removes first-or-last gutters when using `output: float` with margin-gutters.
- Selects the correct columns to span when using asymmetrical grids where columns are not a uniform width.
- Creates an offset **only** when using `output: isolate`, otherwise CSS has no way of knowing what offset is actually needed for the context.
