### ISSUE TITLE
Are containers and span includes removed in 3.0?

### ISSUE THREAD

**Issue by brograhamer** [oddbird/susy#644]
Loving 3.0, but I'm curious if `@include container()` and `@include span()` are being removed? They no longer work with my existing system after updating. If the following is not preferred can you please use the example below to show me how you would do this with Susy instead?

```
#page {
    main {
        @include container();
        article {
            @include span(3 of 4);
        }
        aside {
            @include span(1 of 4);
        }
    }
}
```
Thank you for all your hard work on this. Susy has changed my life within my career, seriously.

**Comment by mirisuzanne** [comment]
Hi @brograhamer –

Yes, all mixins have been removed from Susy3. You can read more about that in the [intro article](http://oddbird.net/2017/06/28/susy3/) and updated [reference docs](http://oddbird.net/susy/docs/).

Replacing the code above would depend on exactly how you have Susy2 set up – since it had so many different output options. The idea now is that you only rely on Susy for math calculations, and make your own decisions about how that math is applied. Here's one way to go:

```scss
main {
  display: flex;
}

article {
  flex-basis: span(3 of 4);
  margin-right: gutter(of 4);
}

aside {
  flex-basis: span(last 1 of 4);
}
```

If you prefer floats, apply the `span()` to `width` instead of `flex-basis`, etc.

**Comment by brograhamer** [comment]
Thank you for your speedy reply and the links, I failed to see the first link but reviewed the new documentation thoroughly. 

Trying to avoid `flex` for now until it's more heavily supported. My biggest question would lie in how I can instantiate rows, so perhaps I'm misunderstanding. I can obviously write a `max-width` and `margin: 0 auto`, but is there a better way to do this in Susy 3.0 that I'm not seeing? Unsure how to phrase the question so I hope you'll understand with the following (would love to pick your brain on this):

```
main {
  max-width: 1000px; // looking for an easier method using Susy for defining a row
  display: block;
  margin: 0 auto;
}

article {
  width: span(3 of 4);
  margin-right: gutter(of 4);
}

aside {
  width: span(last 1 of 4);
}
```

**Comment by mirisuzanne** [comment]
The flexbox support tables [are pretty green](http://caniuse.com/#feat=flexbox), you must be dealing with older browsers?

How you define the row width depends on how your grids are set up. For a fluid grid, that max-width will always be arbitrary. If you are using static grids, it works like any other span (though we do provide an `all` shortcut). Since this is a container, you may want to pass in the `container-spread` setting as well (if it's different from the default `spread` setting):

```scss
main {
  max-width: span(all <container-spread>);
  display: block;
  margin: 0 auto;
}
```

**Comment by brograhamer** [comment]
Apologies for the delay. Yes, we are contractually serving IE9+ at minimum for probably the remainder of the year. This makes perfect sense with your system, thank you! I would say this solves the problem I was running into with 3.0.

**Comment by mirisuzanne** [comment]
Great!

**Comment by AurelianSpodarec** [comment]
Hello @mirisuzanne ,

I'm having the same issue as above, and I'm not sure to get it. 

How would you go about making this in Susy3? 

![image](https://user-images.githubusercontent.com/10155855/29003021-5cee3c4c-7aaf-11e7-92ef-1a1cf2e1ca5c.png)

In Susy2 this was straight forward. You used @include container, susy-clearfix, span(3) - which is the same now. Though how would you make this in Susy3? What about last, first, omega, gallery etc...

 Does this mean we will have to create our own containers etc... like in the vanilla CSS? 

Here you showed us:

```
main {
  max-width: span(all <container-spread>);
  display: block;
  margin: 0 auto;
}
```

So I'm assuming in max-width that is a span(narrow) ? Not sure I get it.

And going with floats, it's as usual, right? But in Susy3 we do it
width: span(6);

And so we get a 50-50 layout, so in my case, the picture about that would be 
width: span(4);

What will be the container of it and about the clearfix after, like Susy2? 

Is there a Documentation like Susy2 where it explains all the commands there are in Susy3? I'm having a hard time to find much on Susy3.

**Comment by mirisuzanne** [comment]
Hi @AurelianSpodarec – I agree that practical examples would be helpful. They also take time, and I'm doing this for free, so it may take me a while. :) I'll keep working on it, and I'm happy for help if you want to write about what you learn.

Since Susy3 no longer includes mixins, you may need a clearfix of your own. You can also create your own container and span mixins if you like - configured to the way you work. I've put together [one example of float-based Susy3 mixins](https://codepen.io/mirisuzanne/pen/VWzwXj?editors=0100). But, with the current state of CSS layout, there is no way for us to optimize those mixins for *every use case*. Your milage will vary, and I highly recommend making changes to fit your specific needs. 

You may also want to start with a global change in box-sizing. We show you how in the [Intro to Susy3](http://oddbird.net/2017/06/28/susy3/). I recommend reading it for a bit more of the thinking behind this release. You're also welcome to keep using Susy2 as long as those defaults make sense to you.
